"""
    vectorized_map_solve(
        probs, alg, ensemblealg::EnsembleArrayAlgorithm, I, adaptive;
        kwargs...
    )

Run the `EnsembleArrayAlgorithm` path directly for a selected set of trajectories. The
function is intended for solver and ensemble package developers that need the lower-level
solution collection without the `EnsembleSolution` construction performed by `solve`.

# Arguments

  - `probs`: the collection of problems generated by the ensemble's `prob_func`.
  - `alg`: a differential-equation algorithm supported by the selected array ensemble
    implementation. OrdinaryDiffEq algorithms are the usual choice.
  - `ensemblealg`: an `EnsembleArrayAlgorithm`, normally `EnsembleGPUArray(backend)` or
    `EnsembleCPUArray()`.
  - `I`: an iterator of trajectory indices, such as `1:10_000`.
  - `adaptive`: whether to use adaptive time stepping.

# Keyword Arguments

Additional solver keywords are forwarded to the underlying differential-equation solve.
Only keywords supported by the selected algorithm and ensemble implementation are valid.

# Returns

The solution returned by the underlying batched solve. Its state arrays contain the selected
trajectories in their second dimension.

# Throws

An `ArgumentError` or `MethodError` can be raised when the problems, algorithm, backend, or
solver keywords are incompatible with the selected array implementation.

# Examples

```julia
sols = DiffEqGPU.vectorized_map_solve(
    probs, Tsit5(), EnsembleCPUArray(), 1:10, false;
    dt = 0.1f0, save_everystep = false
)
```
"""
function vectorized_map_solve end

function vectorized_map_solve(
        probs, alg,
        ensemblealg::Union{EnsembleArrayAlgorithm}, I,
        adaptive;
        kwargs...
    )

    #    @assert all(Base.Fix2((prob1, prob2) -> isequal(prob1.tspan, prob2.tspan),probs[1]),probs)
    # u0 = reduce(hcat, Array(probs[i].u0) for i in 1:length(I))
    # p = reduce(hcat,
    #             probs[i].p isa SciMLBase.NullParameters ? probs[i].p : Array(probs[i].p)
    #             for i in 1:length(I))

    u0 = hcat([Array(probs[i].u0) for i in 1:length(I)]...)
    p = hcat([Array(probs[i].p) for i in 1:length(I)]...)

    prob = probs[1]
    return sol = vectorized_map_solve_up(
        prob, alg, ensemblealg, I, u0, p;
        adaptive = adaptive, kwargs...
    )
end

function vectorized_map_solve_up(prob, alg, ensemblealg, I, u0, p; kwargs...)
    if ensemblealg isa EnsembleGPUArray
        backend = ensemblealg.backend
        u0 = adapt(backend, u0)
        p = adapt(backend, p)
    end

    len = length(prob.u0)

    if SciMLBase.has_jac(prob.f)
        if ensemblealg isa EnsembleGPUArray
            backend = ensemblealg.backend
            jac_prototype = allocate(backend, Float32, (len, len, length(I)))
            fill!(jac_prototype, 0.0)
        else
            jac_prototype = zeros(Float32, len, len, length(I))
        end

        if prob.f.colorvec !== nothing
            colorvec = repeat(prob.f.colorvec, length(I))
        else
            colorvec = repeat(1:length(prob.u0), length(I))
        end
    else
        jac_prototype = nothing
        colorvec = nothing
    end

    _callback = generate_callback(prob, length(I), ensemblealg; kwargs...)
    prob = generate_problem(prob, u0, p, jac_prototype, colorvec)

    if hasproperty(alg, :linsolve)
        _alg = remake(alg, linsolve = LinSolveGPUSplitFactorize(len, -1))
    else
        _alg = alg
    end

    return sol = solve(
        prob, _alg; kwargs..., callback = _callback, merge_callbacks = false,
        internalnorm = diffeqgpunorm
    )
end
