steps:
  - label: "Julia 1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          persist_depot_dirs: ""
      - JuliaCI/julia-test#v1:
           coverage: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  GROUP: GPU
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
