steps:
  - label: ":julia: Run tests on Julia v1 with Apple Metal"
    env:
      GROUP: Metal
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          persist_depot_dirs: ""
    command: julia .ci/develop.jl
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"
    timeout_in_minutes: 120
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/
env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
