name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref_type != 'tag' }}

jobs:
  gpu-docs:
    name: "Documentation"
    runs-on: [self-hosted, gpu-v100]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: "1"
      - run: |
          julia --project=docs -e '
            println("--- Instantiating project")
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            println("+++ Building documentation")
            include("docs/make.jl")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DATADEPS_ALWAYS_ACCEPT: true
